---
stages:
- Python Test
- Python Release

pytest:
  stage: Python Test
  only:
    changes:
      - datalake_ftp/**/*
      - tests/**/*
    refs:
      - branches
  image: 641143039263.dkr.ecr.eu-west-3.amazonaws.com/runner/ci-datalake-ftp:220301
  variables:
    CLAMAV_NO_CLAMD: "false"
    CLAMAV_NO_FRESHCLAMD: "true"
    CLAMAV_NO_MILTERD: "true"
  services:
    - alias: clamav
      name: clamav/clamav:0.104.0
  before_script:
  - poetry install --quiet
  script:
  - poetry run coverage run -m pytest -q --color=no
  - poetry run coverage report -m

pypi-release:
  stage: Python Release
  only:
  - tags
  image: public.ecr.aws/equancy-tech/ci-python:3.8
  script:
  - poetry build --quiet
  - poetry publish -u "${PYPI_USER}" -p "${PYPI_PASSWORD}"
